# Generated by Django 6.0.4 on 2026-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_otp_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="temp_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
