# Generated by Django 6.0.4 on 2026-05-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_meal_status"),
        ("api", "0005_meal_is_featured_subscription"),
    ]

    operations = []
