# Generated by Django 6.0.4 on 2026-05-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_booking_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_new_meals",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_promotions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_reviews",
            field=models.BooleanField(default=True),
        ),
    ]
