# Generated by Django 6.0.4 on 2026-06-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_payment_method_booking_payment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_bookings', to='api.meal'),
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='api.booking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_list', to='api.meal'),
        ),
    ]
