# Generated by Django 6.0.4 on 2026-06-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_preserve_reviews_on_meal_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('completed', 'Completed')], default='none', max_length=20),
        ),
    ]
