# Generated by Django 6.0.4 on 2026-06-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_handed_over',
            field=models.BooleanField(default=False),
        ),
    ]
