# Generated by Django 6.0.4 on 2026-06-22 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_is_handed_over'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('total_earned', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Wallet',
            },
        ),
        migrations.CreateModel(
            name='PlatformTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('reason', models.CharField(choices=[('booking_commission', 'Booking Commission'), ('cancellation_commission', 'Cancellation Commission'), ('withdrawal', 'Withdrawal')], max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('booking_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.platformwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
